frameworkVersion: "3"
service: sls

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1

functions:
  count:
    handler: count
    events:
      - http:
          path: /
          method: get
          cors: true
