service: sls

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1

plugins:
  - serverless-domain-manager

functions:
  count:
    handler: count
    events:
      - http:
          path: /
          method: get
          cors: true

custom:
  customDomain:
    http:
      domainName: sls.dabase.com
      certificateName: "*.dabase.com"
      createRoute53Record: false
      endpointType: regional