service: sls

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-1

functions:
  count:
    handler: count
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  customDomain:
    domainName: sls.goserverless.sg
