AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String
  ACMCertificateArn:
    Type: String

Resources:
  Gateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref ACMCertificateArn

  CountFunction:
    Type: AWS::Serverless::Function
    Architectures:
      - x86_64
    Metadata:
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html
      BuildMethod: makefile
    Properties:
      FunctionName: CountFunction # needed for sam logs!
      CodeUri: ./
      Handler: count
      Runtime: go1.x
      Events:
        CatchAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref Gateway
            Path: /{proxy+}
            Method: ANY

Outputs:
  CountFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt CountFunction.Arn
  CountFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CountFunctionRole.Arn
  GatewayEndPoint:
    Value: !Sub "https://${Gateway}.execute-api.${AWS::Region}.amazonaws.com/"
  CountFunctionLogs:
    Value: !Sub "sam logs --name ${CountFunction} --region ${AWS::Region} --tail"
