name: Deploy Azure function

on:
  push:
    branches:
      - azure-functions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Test
        run: CGO_ENABLED=0 go test -v .
      - name: Setup func env
        uses: Azure/functions-action@v1
      - name: Deploy
        run: make deploy
