name: Deploy Azure function

on:
  push:
    branches:
      - azure-functions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Test
        run: CGO_ENABLED=0 go test -v .

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Login to Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: 'Install Azure Function Core Tools'
        run: 'npm i -g azure-functions-core-tools@3'

      - name: 'Deploy to Azure Functions'
        run: make deploy
