# https://raw.githubusercontent.com/google-github-actions/setup-gcloud/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml

name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - gcp-cloudrun

env:
  PROJECT_ID: idiotbox
  RUN_REGION: asia-southeast1
  SERVICE_NAME: count

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.RUN_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
