# https://raw.githubusercontent.com/google-github-actions/setup-gcloud/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml
name: Build and Deploy to Cloud Run

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  PROJECT_ID: idiotbox
  RUN_REGION: asia-southeast1
  SERVICE_NAME: count

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          project_id: ${{ secrets.RUN_PROJECT }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with: # use source code
          source: .

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
