# https://raw.githubusercontent.com/google-github-actions/setup-gcloud/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml
name: Build and Deploy to Cloud Run

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  PROJECT_ID: idiotbox
  RUN_REGION: asia-southeast1
  SERVICE_NAME: count

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gcp-cloudrun

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          project_id: ${{ secrets.RUN_PROJECT }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ secrets.RUN_PROJECT }}

      - name: "Use gcloud CLI"
        run: "gcloud info"

      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
