# https://github.com/marketplace/actions/lighthouse-ci-action
name: Lighthouse Audit
on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://count.goserverless.sg
          uploadArtifacts: true
          temporaryPublicStorage: true
