name: Deploy via Apex Up

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "stable"
      - name: Build
        run: CGO_ENABLED=0 go build -o server *.go
      - name: Test
        run: CGO_ENABLED=0 go test -v .
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: ap-southeast-1
      - name: Deploy
        uses: apex/actions/up@v0.5.1
        with:
          stage: staging
