name: Deploy via Serverless framework

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: ap-southeast-1
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Compile static Go binary with version info
        run: make
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "serverless plugin install --name serverless-domain-manager && serverless deploy"
          entrypoint: /bin/sh
