name: Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: CGO_ENABLED=0 go build -o server *.go
      - name: Test
        run: CGO_ENABLED=0 go test -v .
      - name: Deploy
        uses: apex/actions/up@v0.5.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          UP_CONFIG: ${{ secrets.UP_CONFIG }}
        with:
          stage: staging
